## Example /usr/local/etc/workspaces.toml configuration file
##
## Adapt for own use.

## Default filesystem to use if none is specified
#default_filesystem = "bulk"

## Location of workspaces database.
##
## It may be convenient to set this to be on the device your workspaces will
## also reside on
#db_path = "/usr/local/lib/workspaces/workspaces.db"

## A definition of a filesystem named `bulk`
#[filesystems.bulk]

## The zpool[/volume] used as a base for the workspaces
#root = "hdd-zpool/ws"

## The maximum duration in days until expiry that can be specified when
## creating or extending datasets
#max_duration = 90

## The number of days after expiration upon which a workspace will be
## flagged for deletion
#expired_retention = 30

## Whether to make snapshots upon maintainance
#snapshot = false

## Whether the filesystem is disabled
##
## Workspaces cannot be created or extended on disabled filesystems.
#disabled = false
