## Example /etc/workspaces/workspaces.toml configuration file
##
## Adapt for own use.

## Default filesystem to use if none is specified
#default_filesystem = "bulk"

## Location of workspaces database.
##
## It may be convenient to set this to be on the device your workspaces will
## also reside on
#db_path = "/usr/local/lib/workspaces/workspaces.db"

## A definition of a filesystem named `bulk`
#[filesystems.bulk]

## The zpool[/volume] used as a base for the workspaces
#root = "hdd-zpool/ws"

## The maximum duration in days until expiry that can be specified when
## creating or extending datasets
#max_duration = 90

## The number of days after expiration upon which a workspace will be
## flagged for deletion
#expired_retention = 30

## Whether to make snapshots during maintainance
#snapshot = false

expiry_notifications = [-29, -25, -20, -10, 0, 7, 14]

## Whether the filesystem is disabled
##
## Workspaces cannot be created or extended on disabled filesystems.
#disabled = false


## Email notifications (SMTP)
##
## Recommended: submit via port 587 with STARTTLS (same as Thunderbird).
## - `relay` can be "host" or "host:port" (also supports "[IPv6]:port").
## - If `from` is omitted, `username` must be a valid email address and will be used as the sender.
## - `auth` is optional; set to "login" or "plain" to force a mechanism, otherwise it auto-negotiates.
## - Usernames with backslashes: either use single-quoted literal strings (no escaping)
##   or escape the backslash in double quotes.
##     Example: # username = 'DOMAIN\svc-workspaces'   # literal (preferred)
##              # username = "DOMAIN\\svc-workspaces"  # basic string with escaping
##
## To enable SMTP, uncomment this whole section and adjust values.
#[smtp]
## Relay hostname (optionally with port). For submission with STARTTLS, use :587.
#relay = "smtp.example.org:587"

## SMTP login name. See backslash note above.
#username = 'DOMAIN\svc-workspaces'

## SMTP password.
#password = "supersecret"

## Optional visible From address; set this if your login is NOT a valid email or
## if you want a nicer sender display. If omitted, falls back to `username`.
#from = "Workspaces Notifier <workspaces-noreply@example.org>"

## Optional: force the auth mechanism. Allowed values: "login", "plain".
## If unset, the client will auto-negotiate.
#auth = "login"
